blueprint:
  name: Yavaş Açılan Işıklar
  description: >
    Belirlenen saatte switch açar, ışığı %10 yakar ve hedef parlaklığa kadar
    yavaşça artırır.
  domain: automation

  input:
    wake_time:
      name: Çalışma Saati
      selector:
        time: {}

    target_light:
      name: Hedef Lamba
      selector:
        entity:
          domain: light

    target_switch:
      name: Açılacak Switch
      selector:
        entity:
          domain: switch

    final_brightness:
      name: Hedef Parlaklık (%)
      default: 65
      selector:
        number:
          min: 1
          max: 100
          step: 1

    step_increase:
      name: Parlaklık Artış Adımı (%)
      default: 5
      selector:
        number:
          min: 1
          max: 20
          step: 1

    step_delay:
      name: Artış Adımları Arası Bekleme (sn)
      default: 25
      selector:
        number:
          min: 1
          max: 120
          step: 1

trigger:
  - platform: time
    at: !input wake_time

action:
  # Switch açık değilse aç
  - choose:
      - conditions:
          - condition: state
            entity_id: !input target_switch
            state: "off"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input target_switch
          - delay: 2

  # Işığı %10 yak
  - service: light.turn_on
    target:
      entity_id: !input target_light
    data:
      brightness_pct: 10

  # Parlaklığı kademeli artır
  - repeat:
      while:
        - condition: template
          value_template: >
            {% set current = state_attr((!input target_light), 'brightness') | int %}
            {% set target = (!input final_brightness | int) * 255 / 100 %}
            {{ current < target }}
      sequence:
        - delay:
            seconds: !input step_delay
        - service: light.turn_on
          target:
            entity_id: !input target_light
          data:
            brightness: >
              {% set current = state_attr((!input target_light), 'brightness') | int %}
              {% set target = (!input final_brightness | int) * 255 / 100 %}
              {% set step = (!input step_increase | int) * 255 / 100 %}
              {{ [current + step, target] | min | int }}

mode: single
