blueprint:
  name: Slow Wake Light
  description: Switch açar, ışığı %10’dan hedef parlaklığa kadar yavaşça artırır.
  domain: automation
  input:
    wake_time:
      name: Çalışma Saati
      selector:
        time: {}
    target_light:
      name: Hedef Lamba
      selector:
        entity:
          domain: light
    target_switch:
      name: Açılacak Switch
      selector:
        entity:
          domain: switch
    final_brightness:
      name: Hedef Parlaklık (%)
      default: 65
      selector:
        number:
          min: 1
          max: 100
    step_increase:
      name: Artış Adımı (%)
      default: 5
      selector:
        number:
          min: 1
          max: 20
    step_delay:
      name: Adımlar Arası Bekleme (sn)
      default: 25
      selector:
        number:
          min: 1
          max: 120

trigger:
  - platform: time
    at: !input wake_time

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input target_switch
            state: 'off'
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input target_switch
          - delay: "00:00:02"

  - service: light.turn_on
    target:
      entity_id: !input target_light
    data:
      brightness_pct: 10

  - repeat:
      while:
        - condition: template
          value_template: >
            {% set light = states[inputs.target_light] %}
            {% if light is none %}
              false
            {% else %}
              {% set current = light.attributes.brightness | int(0) %}
              {% set target_b = (inputs.final_brightness | int) * 255 / 100 %}
              {{ current < target_b }}
            {% endif %}
      sequence:
        - delay:
            seconds: "{{ inputs.step_delay }}"
        - service: light.turn_on
          target:
            entity_id: !input target_light
          data:
            brightness: >
              {% set light = states[inputs.target_light] %}
              {% set current = light.attributes.brightness | int(0) %}
              {% set target_b = (inputs.final_brightness | int) * 255 / 100 %}
              {% set step_b = (inputs.step_increase | int) * 255 / 100 %}
              {{ [current + step_b, target_b] | min | int }}

mode: single
